name: LHCI-lighthouse-plugin
on: push
jobs:
  lighthouse-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn add --no-lockfile lighthouse-plugin-field-performance
      - name: Audit URLs with Field Performance Plugin
        uses: ./
        with:
          urls: |
            https://www.example.com/
          configPath: '.github/lighthouse/lighthouserc-plugin.js'
          temporaryPublicStorage: true
