# This is an advanced fully hermetic run of Lighthouse, using custom config.
name: LHCI-hermetic-advanced
on: push
jobs:
  hermetic-advanced:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Lighthouse on urls with lighthouserc
        uses: ./
        with:
          urls: 'https://alekseykulikov.com/'
          configPath: '.github/lighthouse/lighthouserc_custom_config.json'
      - name: Save .lighthouseci artifacts
        uses: actions/upload-artifact@v1
        with:
          name: advanced-hermetic-artifacts
          path: '.lighthouseci'
